// Generated by CoffeeScript 1.9.1
var _deep_equal, _empty, a, an, be, contain, deep_equal, does_exist, empty, eq, eql, equal, error, exist, expect, greater, greater_or_equal, greater_than, gt, gte, have, include, is_empty, is_ok, length, less, less_or_equal, less_than, lt, lte, match, negate, neq, not_equal, nt, ok, sentence, should_throw, str, than, to, truthy, wassat;

_deep_equal = require("deep-equal");

_empty = require("lodash.isempty");

wassat = require("wassat");

str = function(v) {
  if (wassat.isArray(v) || wassat.isObject(v)) {
    return JSON.stringify(v);
  }
  if (wassat.isFunction(v)) {
    return "<" + (v.name || "anonymous function") + ">";
  }
  if (wassat.isString(v)) {
    return "\"" + v + "\"";
  }
  return String(v);
};

exist = {};

empty = {};

error = {};

ok = truthy = {};

is_empty = function(x) {
  return [_empty(x), "expected " + (str(x)) + " to be empty"];
};

is_ok = function(x) {
  return [!!x, "expected " + (str(x)) + " to be truthy"];
};

does_exist = function(x) {
  return [x != null, "expected " + (str(x)) + " to exist"];
};

should_throw = function(f) {
  var e;
  return [
    ((function() {
      try {
        f();
      } catch (_error) {
        e = _error;
      }
      return e != null;
    })()), "expected function to throw an error"
  ];
};

expect = function(x) {
  return function(y) {
    var label, okay, ref;
    if (!wassat.isFunction(y)) {
      throw new Error("Pass a function");
    }
    ref = y(x), okay = ref[0], label = ref[1];
    if (!okay) {
      throw new Error(label);
    }
  };
};

than = function(x) {
  return x;
};

eq = equal = function(y) {
  return function(x) {
    return [x === y, "expected " + (str(x)) + " to equal " + (str(y))];
  };
};

neq = not_equal = function(y) {
  return function(x) {
    return [x !== y, "expected " + (str(x)) + " to not equal " + (str(y))];
  };
};

eql = deep_equal = function(x) {
  return function(y) {
    return [
      _deep_equal(x, y, {
        strict: true
      }), "expected " + (str(x)) + " to deep equal " + (str(y))
    ];
  };
};

gt = greater = greater_than = function(y) {
  return function(x) {
    return [x > y, "expected " + (str(x)) + " to be greater than " + (str(y))];
  };
};

lt = less = less_than = function(y) {
  return function(x) {
    return [x < y, "expected " + (str(x)) + " to be less than " + (str(y))];
  };
};

gte = greater_or_equal = function(y) {
  return function(x) {
    return [x >= y, "expected " + (str(x)) + " to be greater than or equal to " + (str(y))];
  };
};

lte = less_or_equal = function(y) {
  return function(x) {
    return [x <= y, "expected " + (str(x)) + " to be less than or equal to " + (str(y))];
  };
};

contain = include = function(x) {
  return function(y) {
    return [y.indexOf(x) !== -1, "expected " + (str(y)) + " to contain " + (str(x))];
  };
};

length = function(x) {
  return function(y) {
    return [y.length === x, "expected " + (str(y)) + " to have `length` " + (str(x))];
  };
};

match = function(x) {
  return function(y) {
    return [x.test(y), "expected " + (str(y)) + " to match " + (str(x))];
  };
};

negate = function(f) {
  return function(x) {
    var label, okay, ref;
    ref = f(x), okay = ref[0], label = ref[1];
    return [!okay, label.replace("expected", "did not expect")];
  };
};

have = function(p) {
  if (wassat.isFunction(p)) {
    return p;
  }
  return function(x) {
    return function(y) {
      return [y[p] === x, "expected property " + (str(p)) + " of " + (str(y)) + " to equal " + (str(x))];
    };
  };
};

a = an = function(x) {
  return function(y) {
    if (x === Object) {
      return [y instanceof x, "expected " + (str(y)) + " to be an instance of " + x.name];
    }
    return [Object(y) instanceof x, "expected " + (str(y)) + " to be an instance of " + x.name];
  };
};

be = to = function(x) {
  switch (x) {
    case empty:
      return is_empty;
    case ok:
      return is_ok;
    case exist:
      return does_exist;
    case error:
      return should_throw;
    default:
      return x;
  }
};

nt = function(f) {
  switch (f) {
    case empty:
      return negate(is_empty);
    case ok:
      return negate(is_ok);
    case exist:
      return negate(does_exist);
    case error:
      return negate(should_throw);
    default:
      return negate(f);
  }
};

sentence = module.exports = {
  exist: exist,
  empty: empty,
  ok: ok,
  error: error,
  a: a,
  an: an,
  have: have,
  match: match,
  length: length,
  contain: contain,
  include: include,
  negate: negate,
  nt: nt,
  to: to,
  be: be,
  than: than,
  less: less,
  lt: lt,
  less_than: less_than,
  less_or_equal: less_or_equal,
  lte: lte,
  greater: greater,
  gt: gt,
  greater_than: greater_than,
  greater_or_equal: greater_or_equal,
  gte: gte,
  expect: expect,
  equal: equal,
  not_equal: not_equal,
  deep_equal: deep_equal,
  eql: eql
};

Object.defineProperty(sentence, "globals", {
  value: function() {
    Object.keys(sentence).forEach(function(k) {
      return global[k] = sentence[k];
    });
    return sentence;
  }
});
