// Generated by CoffeeScript 1.9.1
var a, an, be, contain, does_exist, empty, eq, equal, error, exist, expect, greater, greater_or_equal, greater_than, gt, gte, have, include, is_empty, is_ok, length, less, less_or_equal, less_than, lt, lte, match, negate, neq, not_equal, nt, ok, sentence, should_throw, than, to, truthy;

exist = {};

empty = {};

error = {};

ok = truthy = {};

is_empty = require("lodash.isempty");

is_ok = function(x) {
  return !!x;
};

does_exist = function(x) {
  return x != null;
};

should_throw = function(f) {
  var e;
  try {
    f();
  } catch (_error) {
    e = _error;
  }
  return e != null;
};

expect = function(x) {
  return function(y) {
    if (typeof y !== "function") {
      throw new Error("Pass a function");
    }
    if (!y(x)) {
      throw new Error("Expectation failed.");
    }
  };
};

than = function(x) {
  return x;
};

eq = equal = function(y) {
  return function(x) {
    return x === y;
  };
};

neq = not_equal = function(y) {
  return function(x) {
    return x !== y;
  };
};

gt = greater = greater_than = function(y) {
  return function(x) {
    return x > y;
  };
};

lt = less = less_than = function(y) {
  return function(x) {
    return x < y;
  };
};

gte = greater_or_equal = function(y) {
  return function(x) {
    return x >= y;
  };
};

lte = less_or_equal = function(y) {
  return function(x) {
    return x <= y;
  };
};

negate = function(f) {
  return function(x) {
    return !f(x);
  };
};

contain = include = function(x) {
  return function(y) {
    return y.indexOf(x) !== -1;
  };
};

length = function(x) {
  return function(y) {
    return y.length === x;
  };
};

match = function(x) {
  return function(y) {
    return x.test(y);
  };
};

have = function(p) {
  if (typeof p === "function") {
    return p;
  }
  return function(x) {
    return function(y) {
      return y[p] === x;
    };
  };
};

a = an = function(x) {
  return function(y) {
    if (x === Object) {
      return y instanceof x;
    }
    return Object(y) instanceof x;
  };
};

be = to = function(x) {
  if (x === empty) {
    return is_empty;
  }
  if (x === ok) {
    return is_ok;
  }
  if (x === exist) {
    return does_exist;
  }
  if (x === error) {
    return should_throw;
  }
  return x;
};

nt = function(f) {
  if (f === empty) {
    return negate(is_empty);
  }
  if (f === ok) {
    return negate(is_ok);
  }
  if (f === exist) {
    return negate(does_exist);
  }
  if (f === error) {
    return negate(should_throw);
  }
  return negate(f);
};

sentence = module.exports = {
  exist: exist,
  empty: empty,
  ok: ok,
  error: error,
  a: a,
  an: an,
  have: have,
  match: match,
  length: length,
  contain: contain,
  include: include,
  negate: negate,
  nt: nt,
  to: to,
  be: be,
  than: than,
  less: less,
  lt: lt,
  less_than: less_than,
  less_or_equal: less_or_equal,
  lte: lte,
  greater: greater,
  gt: gt,
  greater_than: greater_than,
  greater_or_equal: greater_or_equal,
  gte: gte,
  expect: expect,
  equal: equal,
  not_equal: not_equal
};

Object.defineProperty(sentence, "globals", {
  value: function() {
    Object.keys(sentence).forEach(function(k) {
      return global[k] = sentence[k];
    });
    return sentence;
  }
});
